name: Build iBudget (Angular App)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ibudget:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/ibudget
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/ibudget/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      #- name: Install Playwright Browsers
      #  run: npx playwright install --with-deps chromium

      #- name: Run tests
      #  run: npm run test -- --watch=false --browsers=ChromeHeadless
      #  env:
      #    CHROME_BIN: /root/.cache/ms-playwright/chromium-1194/chrome-linux/chrome

      - name: Build project
        run: npm run build --if-present